# Generated by Django 3.2.9 on 2021-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactid',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
